import { useState } from 'react';
import Paper from './paper/Paper';
import style from '../Submit/sub.css'
import { BrowserRouter, Routes, Route } from "react-router-dom";
import { Link } from "react-router-dom";
import Header from "../Header/header"
import {Footer} from "../Footer/footer"
// import Link from 'next/link';
export default function Home() {

    // const output = [];
    const topics = [["12312", 'Affinity among AI and DB', 1678168800, 'new'], ["23423", 'DNA memory and its significance', 1678168800, ''], ["82738", 'Internet of Things with Classrooms', 1678168800, 'new'], ["94338", 'Importantance of DataBase', 1677909600, ""], ["82342", "Innovations on Air cooling", 1685854800, ''], ["58384", "Implementation of Java in Class", 1685854800, '']]
    const [output, setoutput] = useState(topics);
    const [nomatch, setnomatch] = useState("");
    function filter(e) {
        var dummy = []
        var newdummy = []
        var TempOutput = []
        console.log("entered value is " + e)
        setoutput([])
        if (e != "") {
            topics.forEach(element => {
                if (element[1].toLocaleLowerCase().includes(e.toLocaleLowerCase()) || element[0].toLocaleLowerCase().includes(e.toLocaleLowerCase())) {
                    setnomatch("")

                    if (element[3] == "new") {
                        newdummy.push(element)
                    }
                    else {
                        dummy.push(element)
                    }
                    TempOutput = newdummy.concat(dummy)
                    setoutput(newdummy.concat(dummy))
                }
            });
        } else {
            topics.forEach(element => {
                if (element[3] == "new") {
                    newdummy.push(element)
                }
                else {
                    dummy.push(element)
                }
                setoutput(newdummy.concat(dummy))
            });

            setoutput(topics)

        }
        if (TempOutput.length == 0 && e != "") {
            setnomatch("No Results Found!!")
        }
        else {
            setnomatch("")
        }

    }
    function toNormal(unix) {
        // var d = new Date(unix*1000);
        let d = new Intl.DateTimeFormat('en-US', { year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', second: '2-digit' }).format(unix * 1000)
        return d
    }
    return (
        <>
            <head>
                <title>Submission</title>
                <meta name="Submit Paper" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous"></link>
                <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet" />
                <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
                <script src="https://cdn.jsdelivr.net/npm/react/umd/react.production.min.js" crossorigin></script>
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.2.1/css/fontawesome.min.css" integrity="sha384-QYIZto+st3yW+o8+5OHfT6S482Zsvz2WfOzpFSXMF9zqeLcFV0/wlZpMtyFcZALm" crossorigin="anonymous" />
                <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
                <script
                    src="https://cdn.jsdelivr.net/npm/react-dom/umd/react-dom.production.min.js"
                    crossorigin></script>
                <link rel="stylesheet"
                    href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
                    integrity="sha384- 
 50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
                    crossorigin="anonymous"></link>
                <script
                    src="https://cdn.jsdelivr.net/npm/react-bootstrap@next/dist/react-bootstrap.min.js"
                    crossorigin></script>
                <script src="https://cdn.jsdelivr.net/npm/react/umd/react.production.min.js" crossorigin></script>

                <script
                    src="https://cdn.jsdelivr.net/npm/react-dom/umd/react-dom.production.min.js"
                    crossorigin></script>

                <script
                    src="https://cdn.jsdelivr.net/npm/react-bootstrap@next/dist/react-bootstrap.min.js"
                    crossorigin></script>

            </head>
            <Header></Header>
            <div className="main" >
                <div>
                    <input className="searchInput" onInputCapture={(e) => filter(e.target.value)} type="text" placeholder='Search..' />
                </div>

                <div className="topic" >

                    {(nomatch != "") ? <p className="no">{nomatch}</p> : <>
                        <div className="topicrow" style={{ marginTop: 50, fontWeight: 'bolder' }}>
                            <div>ID</div>
                            <div>Topic</div>
                            <div>Due Date</div>
                            <div>Links
                            </div>
                        </div></>}
                    {output.map((topic) =>
                        <div className="topicrow">
                            <div>
                                {topic[0]}
                            </div>
                            <div>{topic[1]}</div>
                            <div>{toNormal(topic[2])}</div>
                            {/* 
                            <div> <Link
                                href={{
                                    pathname: `/Submit/paper`,
                                    state: { Tid: topic[0] }
                                }}
                            >Submit</Link> </div> */}
                            <div><a className="a" href="/Submit/paper/">Submit</a></div>
                        </div>)}
                </div>
            </div>
            <Footer></Footer>
        </>
    )

}